name: CI - Controle Migração

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.10, 3.11, 3.12]

    steps:
    - name: Checkout código
      uses: actions/checkout@v4

    - name: Configurar Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Instalar dependências
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install flake8 black pytest pytest-cov

    # - name: Rodar Flake8
    #   run: flake8

    - name: Rodar Pytest com cobertura
      run: pytest --cov=controle_migracao tests/

    - name: Gerar relatório de cobertura
      run: coverage xml
